# Generated by Django 3.2.8 on 2021-10-24 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5, message='Must input rating between 0 - 5'), django.core.validators.MinValueValidator(0, message='Must input rating between 0 - 5')]),
        ),
    ]
